-- Seed Teams Migration
-- Inserts all 210 teams into the database (curado 2026-07-20: FIFA membership real,
-- Israel->Africa, Uzbekistan->Europe, American Samoa eliminada; skills recalibrados
-- contra el ranking FIFA del 20-jul-2026)
-- Execute this after running schema.sql

BEGIN;

-- Clear existing teams (optional - remove if you want to keep existing data)
-- DELETE FROM teams;

-- Insert all teams
INSERT INTO teams (id, name, flag, region, skill) VALUES
  ('ger', 'Germany', 'https://flagsapi.com/DE/flat/64.png', 'Europe', 82),
  ('fra', 'France', 'https://flagsapi.com/FR/flat/64.png', 'Europe', 88),
  ('esp', 'Spain', 'https://flagsapi.com/ES/flat/64.png', 'Europe', 90),
  ('ita', 'Italy', 'https://flagsapi.com/IT/flat/64.png', 'Europe', 80),
  ('eng', 'England', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/320px-Flag_of_England.svg.png', 'Europe', 87),
  ('ned', 'Netherlands', 'https://flagsapi.com/NL/flat/64.png', 'Europe', 84),
  ('por', 'Portugal', 'https://flagsapi.com/PT/flat/64.png', 'Europe', 85),
  ('bel', 'Belgium', 'https://flagsapi.com/BE/flat/64.png', 'Europe', 85),
  ('cro', 'Croatia', 'https://flagsapi.com/HR/flat/64.png', 'Europe', 82),
  ('den', 'Denmark', 'https://flagsapi.com/DK/flat/64.png', 'Europe', 78),
  ('sui', 'Switzerland', 'https://flagsapi.com/CH/flat/64.png', 'Europe', 81),
  ('aut', 'Austria', 'https://flagsapi.com/AT/flat/64.png', 'Europe', 77),
  ('swe', 'Sweden', 'https://flagsapi.com/SE/flat/64.png', 'Europe', 74),
  ('pol', 'Poland', 'https://flagsapi.com/PL/flat/64.png', 'Europe', 74),
  ('ukr', 'Ukraine', 'https://flagsapi.com/UA/flat/64.png', 'Europe', 75),
  ('ser', 'Serbia', 'https://flagsapi.com/RS/flat/64.png', 'Europe', 73),
  ('tur', 'Turkey', 'https://flagsapi.com/TR/flat/64.png', 'Europe', 76),
  ('cze', 'Czech Republic', 'https://flagsapi.com/CZ/flat/64.png', 'Europe', 72),
  ('wal', 'Wales', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/320px-Flag_of_Wales.svg.png', 'Europe', 74),
  ('sco', 'Scotland', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Flag_of_Scotland.svg/320px-Flag_of_Scotland.svg.png', 'Europe', 73),
  ('nor', 'Norway', 'https://flagsapi.com/NO/flat/64.png', 'Europe', 79),
  ('rus', 'Russia', 'https://flagsapi.com/RU/flat/64.png', 'Europe', 74),
  ('rou', 'Romania', 'https://flagsapi.com/RO/flat/64.png', 'Europe', 70),
  ('hun', 'Hungary', 'https://flagsapi.com/HU/flat/64.png', 'Europe', 73),
  ('gre', 'Greece', 'https://flagsapi.com/GR/flat/64.png', 'Europe', 72),
  ('svk', 'Slovakia', 'https://flagsapi.com/SK/flat/64.png', 'Europe', 72),
  ('fin', 'Finland', 'https://flagsapi.com/FI/flat/64.png', 'Europe', 66),
  ('bih', 'Bosnia and Herzegovina', 'https://flagsapi.com/BA/flat/64.png', 'Europe', 68),
  ('isl', 'Iceland', 'https://flagsapi.com/IS/flat/64.png', 'Europe', 66),
  ('ire', 'Republic of Ireland', 'https://flagsapi.com/IE/flat/64.png', 'Europe', 69),
  ('nir', 'Northern Ireland', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Northern_Ireland_%281953%E2%80%931972%29.svg/320px-Flag_of_Northern_Ireland_%281953%E2%80%931972%29.svg.png', 'Europe', 66),
  ('alb', 'Albania', 'https://flagsapi.com/AL/flat/64.png', 'Europe', 67),
  ('svn', 'Slovenia', 'https://flagsapi.com/SI/flat/64.png', 'Europe', 69),
  ('mkd', 'North Macedonia', 'https://flagsapi.com/MK/flat/64.png', 'Europe', 67),
  ('bul', 'Bulgaria', 'https://flagsapi.com/BG/flat/64.png', 'Europe', 64),
  ('mne', 'Montenegro', 'https://flagsapi.com/ME/flat/64.png', 'Europe', 65),
  ('isr', 'Israel', 'https://flagsapi.com/IL/flat/64.png', 'Africa', 65),
  ('geo', 'Georgia', 'https://flagsapi.com/GE/flat/64.png', 'Europe', 66),
  ('arm', 'Armenia', 'https://flagsapi.com/AM/flat/64.png', 'Europe', 60),
  ('aze', 'Azerbaijan', 'https://flagsapi.com/AZ/flat/64.png', 'Europe', 58),
  ('kaz', 'Kazakhstan', 'https://flagsapi.com/KZ/flat/64.png', 'Europe', 60),
  ('blr', 'Belarus', 'https://flagsapi.com/BY/flat/64.png', 'Europe', 62),
  ('lux', 'Luxembourg', 'https://flagsapi.com/LU/flat/64.png', 'Europe', 62),
  ('cyp', 'Cyprus', 'https://flagsapi.com/CY/flat/64.png', 'Europe', 58),
  ('est', 'Estonia', 'https://flagsapi.com/EE/flat/64.png', 'Europe', 58),
  ('lva', 'Latvia', 'https://flagsapi.com/LV/flat/64.png', 'Europe', 56),
  ('ltu', 'Lithuania', 'https://flagsapi.com/LT/flat/64.png', 'Europe', 55),
  ('fro', 'Faroe Islands', 'https://flagsapi.com/FO/flat/64.png', 'Europe', 58),
  ('mlt', 'Malta', 'https://flagsapi.com/MT/flat/64.png', 'Europe', 54),
  ('mda', 'Moldova', 'https://flagsapi.com/MD/flat/64.png', 'Europe', 54),
  ('kos', 'Kosovo', 'https://flagsapi.com/XK/flat/64.png', 'Europe', 65),
  ('lie', 'Liechtenstein', 'https://flagsapi.com/LI/flat/64.png', 'Europe', 35),
  ('and', 'Andorra', 'https://flagsapi.com/AD/flat/64.png', 'Europe', 52),
  ('smr', 'San Marino', 'https://flagsapi.com/SM/flat/64.png', 'Europe', 30),
  ('gib', 'Gibraltar', 'https://flagsapi.com/GI/flat/64.png', 'Europe', 39),
  ('bra', 'Brazil', 'https://flagsapi.com/BR/flat/64.png', 'America', 86),
  ('arg', 'Argentina', 'https://flagsapi.com/AR/flat/64.png', 'America', 89),
  ('uru', 'Uruguay', 'https://flagsapi.com/UY/flat/64.png', 'America', 78),
  ('col', 'Colombia', 'https://flagsapi.com/CO/flat/64.png', 'America', 83),
  ('chi', 'Chile', 'https://flagsapi.com/CL/flat/64.png', 'America', 71),
  ('par', 'Paraguay', 'https://flagsapi.com/PY/flat/64.png', 'America', 74),
  ('ecu', 'Ecuador', 'https://flagsapi.com/EC/flat/64.png', 'America', 77),
  ('per', 'Peru', 'https://flagsapi.com/PE/flat/64.png', 'America', 71),
  ('ven', 'Venezuela', 'https://flagsapi.com/VE/flat/64.png', 'America', 72),
  ('bol', 'Bolivia', 'https://flagsapi.com/BO/flat/64.png', 'America', 65),
  ('mex', 'Mexico', 'https://flagsapi.com/MX/flat/64.png', 'America', 84),
  ('usa', 'United States', 'https://flagsapi.com/US/flat/64.png', 'America', 80),
  ('can', 'Canada', 'https://flagsapi.com/CA/flat/64.png', 'America', 75),
  ('crc', 'Costa Rica', 'https://flagsapi.com/CR/flat/64.png', 'America', 71),
  ('jam', 'Jamaica', 'https://flagsapi.com/JM/flat/64.png', 'America', 66),
  ('pan', 'Panama', 'https://flagsapi.com/PA/flat/64.png', 'America', 73),
  ('hon', 'Honduras', 'https://flagsapi.com/HN/flat/64.png', 'America', 67),
  ('slv', 'El Salvador', 'https://flagsapi.com/SV/flat/64.png', 'America', 62),
  ('tri', 'Trinidad and Tobago', 'https://flagsapi.com/TT/flat/64.png', 'America', 61),
  ('hti', 'Haiti', 'https://flagsapi.com/HT/flat/64.png', 'America', 64),
  ('cub', 'Cuba', 'https://flagsapi.com/CU/flat/64.png', 'America', 53),
  ('gua', 'Guatemala', 'https://flagsapi.com/GT/flat/64.png', 'America', 62),
  ('nic', 'Nicaragua', 'https://flagsapi.com/NI/flat/64.png', 'America', 57),
  ('sur', 'Suriname', 'https://flagsapi.com/SR/flat/64.png', 'America', 58),
  ('brb', 'Barbados', 'https://flagsapi.com/BB/flat/64.png', 'America', 51),
  ('dom', 'Dominican Republic', 'https://flagsapi.com/DO/flat/64.png', 'America', 56),
  ('ber', 'Bermuda', 'https://flagsapi.com/BM/flat/64.png', 'America', 53),
  ('blz', 'Belize', 'https://flagsapi.com/BZ/flat/64.png', 'America', 51),
  ('guy', 'Guyana', 'https://flagsapi.com/GY/flat/64.png', 'America', 55),
  ('pue', 'Puerto Rico', 'https://flagsapi.com/PR/flat/64.png', 'America', 55),
  ('cuw', 'Curaçao', 'https://flagsapi.com/CW/flat/64.png', 'America', 64),
  ('atg', 'Antigua and Barbuda', 'https://flagsapi.com/AG/flat/64.png', 'America', 54),
  ('skn', 'Saint Kitts and Nevis', 'https://flagsapi.com/KN/flat/64.png', 'America', 55),
  ('lca', 'Saint Lucia', 'https://flagsapi.com/LC/flat/64.png', 'America', 53),
  ('vin', 'Saint Vincent and the Grenadines', 'https://flagsapi.com/VC/flat/64.png', 'America', 52),
  ('grn', 'Grenada', 'https://flagsapi.com/GD/flat/64.png', 'America', 53),
  ('msr', 'Montserrat', 'https://flagsapi.com/MS/flat/64.png', 'America', 52),
  ('dma', 'Dominica', 'https://flagsapi.com/DM/flat/64.png', 'America', 51),
  ('aru', 'Aruba', 'https://flagsapi.com/AW/flat/64.png', 'America', 48),
  ('cay', 'Cayman Islands', 'https://flagsapi.com/KY/flat/64.png', 'America', 45),
  ('bah', 'Bahamas', 'https://flagsapi.com/BS/flat/64.png', 'America', 34),
  ('tca', 'Turks and Caicos Islands', 'https://flagsapi.com/TC/flat/64.png', 'America', 35),
  ('vgb', 'British Virgin Islands', 'https://flagsapi.com/VG/flat/64.png', 'America', 31),
  ('vir', 'US Virgin Islands', 'https://flagsapi.com/VI/flat/64.png', 'America', 32),
  ('aia', 'Anguilla', 'https://flagsapi.com/AI/flat/64.png', 'America', 31),
  ('sen', 'Senegal', 'https://flagsapi.com/SN/flat/64.png', 'Africa', 79),
  ('mar', 'Morocco', 'https://flagsapi.com/MA/flat/64.png', 'Africa', 85),
  ('tun', 'Tunisia', 'https://flagsapi.com/TN/flat/64.png', 'Africa', 69),
  ('alg', 'Algeria', 'https://flagsapi.com/DZ/flat/64.png', 'Africa', 75),
  ('egy', 'Egypt', 'https://flagsapi.com/EG/flat/64.png', 'Africa', 77),
  ('nga', 'Nigeria', 'https://flagsapi.com/NG/flat/64.png', 'Africa', 76),
  ('cmr', 'Cameroon', 'https://flagsapi.com/CM/flat/64.png', 'Africa', 73),
  ('gha', 'Ghana', 'https://flagsapi.com/GH/flat/64.png', 'Africa', 67),
  ('civ', 'Ivory Coast', 'https://flagsapi.com/CI/flat/64.png', 'Africa', 75),
  ('mli', 'Mali', 'https://flagsapi.com/ML/flat/64.png', 'Africa', 70),
  ('bfa', 'Burkina Faso', 'https://flagsapi.com/BF/flat/64.png', 'Africa', 68),
  ('cgo', 'Congo DR', 'https://flagsapi.com/CD/flat/64.png', 'Africa', 73),
  ('zaf', 'South Africa', 'https://flagsapi.com/ZA/flat/64.png', 'Africa', 70),
  ('gab', 'Gabon', 'https://flagsapi.com/GA/flat/64.png', 'Africa', 64),
  ('gui', 'Guinea', 'https://flagsapi.com/GN/flat/64.png', 'Africa', 65),
  ('cap', 'Cape Verde', 'https://flagsapi.com/CV/flat/64.png', 'Africa', 67),
  ('uga', 'Uganda', 'https://flagsapi.com/UG/flat/64.png', 'Africa', 63),
  ('zam', 'Zambia', 'https://flagsapi.com/ZM/flat/64.png', 'Africa', 63),
  ('ken', 'Kenya', 'https://flagsapi.com/KE/flat/64.png', 'Africa', 60),
  ('mad', 'Madagascar', 'https://flagsapi.com/MG/flat/64.png', 'Africa', 61),
  ('mau', 'Mauritania', 'https://flagsapi.com/MR/flat/64.png', 'Africa', 60),
  ('ben', 'Benin', 'https://flagsapi.com/BJ/flat/64.png', 'Africa', 63),
  ('nig', 'Niger', 'https://flagsapi.com/NE/flat/64.png', 'Africa', 59),
  ('tog', 'Togo', 'https://flagsapi.com/TG/flat/64.png', 'Africa', 59),
  ('gui-bis', 'Guinea-Bissau', 'https://flagsapi.com/GW/flat/64.png', 'Africa', 57),
  ('rwa', 'Rwanda', 'https://flagsapi.com/RW/flat/64.png', 'Africa', 57),
  ('bdi', 'Burundi', 'https://flagsapi.com/BI/flat/64.png', 'Africa', 56),
  ('eth', 'Ethiopia', 'https://flagsapi.com/ET/flat/64.png', 'Africa', 56),
  ('tan', 'Tanzania', 'https://flagsapi.com/TZ/flat/64.png', 'Africa', 60),
  ('zim', 'Zimbabwe', 'https://flagsapi.com/ZW/flat/64.png', 'Africa', 57),
  ('nam', 'Namibia', 'https://flagsapi.com/NA/flat/64.png', 'Africa', 58),
  ('moz', 'Mozambique', 'https://flagsapi.com/MZ/flat/64.png', 'Africa', 61),
  ('ang', 'Angola', 'https://flagsapi.com/AO/flat/64.png', 'Africa', 64),
  ('lbr', 'Liberia', 'https://flagsapi.com/LR/flat/64.png', 'Africa', 56),
  ('sle', 'Sierra Leone', 'https://flagsapi.com/SL/flat/64.png', 'Africa', 58),
  ('mal', 'Malawi', 'https://flagsapi.com/MW/flat/64.png', 'Africa', 57),
  ('cgob', 'Congo', 'https://flagsapi.com/CG/flat/64.png', 'Africa', 57),
  ('eqg', 'Equatorial Guinea', 'https://flagsapi.com/GQ/flat/64.png', 'Africa', 61),
  ('cta', 'Central African Republic', 'https://flagsapi.com/CF/flat/64.png', 'Africa', 56),
  ('cha', 'Chad', 'https://flagsapi.com/TD/flat/64.png', 'Africa', 50),
  ('stp', 'São Tomé and Príncipe', 'https://flagsapi.com/ST/flat/64.png', 'Africa', 46),
  ('gam', 'Gambia', 'https://flagsapi.com/GM/flat/64.png', 'Africa', 59),
  ('mri', 'Mauritius', 'https://flagsapi.com/MU/flat/64.png', 'Africa', 51),
  ('com', 'Comoros', 'https://flagsapi.com/KM/flat/64.png', 'Africa', 60),
  ('sey', 'Seychelles', 'https://flagsapi.com/SC/flat/64.png', 'Africa', 36),
  ('dji', 'Djibouti', 'https://flagsapi.com/DJ/flat/64.png', 'Africa', 46),
  ('som', 'Somalia', 'https://flagsapi.com/SO/flat/64.png', 'Africa', 41),
  ('ssd', 'South Sudan', 'https://flagsapi.com/SS/flat/64.png', 'Africa', 52),
  ('eri', 'Eritrea', 'https://flagsapi.com/ER/flat/64.png', 'Africa', 50),
  ('les', 'Lesotho', 'https://flagsapi.com/LS/flat/64.png', 'Africa', 55),
  ('bot', 'Botswana', 'https://flagsapi.com/BW/flat/64.png', 'Africa', 55),
  ('swa', 'Eswatini', 'https://flagsapi.com/SZ/flat/64.png', 'Africa', 53),
  ('lby', 'Libya', 'https://flagsapi.com/LY/flat/64.png', 'Africa', 60),
  ('sud', 'Sudan', 'https://flagsapi.com/SD/flat/64.png', 'Africa', 59),
  ('jpn', 'Japan', 'https://flagsapi.com/JP/flat/64.png', 'Asia', 79),
  ('kor', 'South Korea', 'https://flagsapi.com/KR/flat/64.png', 'Asia', 75),
  ('irn', 'Iran', 'https://flagsapi.com/IR/flat/64.png', 'Asia', 78),
  ('aus', 'Australia', 'https://flagsapi.com/AU/flat/64.png', 'Asia', 76),
  ('sau', 'Saudi Arabia', 'https://flagsapi.com/SA/flat/64.png', 'Asia', 68),
  ('qat', 'Qatar', 'https://flagsapi.com/QA/flat/64.png', 'Asia', 68),
  ('uae', 'UAE', 'https://flagsapi.com/AE/flat/64.png', 'Asia', 67),
  ('irq', 'Iraq', 'https://flagsapi.com/IQ/flat/64.png', 'Asia', 68),
  ('chn', 'China', 'https://flagsapi.com/CN/flat/64.png', 'Asia', 63),
  ('uzb', 'Uzbekistan', 'https://flagsapi.com/UZ/flat/64.png', 'Europe', 68),
  ('tha', 'Thailand', 'https://flagsapi.com/TH/flat/64.png', 'Asia', 63),
  ('vie', 'Vietnam', 'https://flagsapi.com/VN/flat/64.png', 'Asia', 62),
  ('omn', 'Oman', 'https://flagsapi.com/OM/flat/64.png', 'Asia', 65),
  ('jor', 'Jordan', 'https://flagsapi.com/JO/flat/64.png', 'Asia', 66),
  ('bhr', 'Bahrain', 'https://flagsapi.com/BH/flat/64.png', 'Asia', 63),
  ('syr', 'Syria', 'https://flagsapi.com/SY/flat/64.png', 'Asia', 64),
  ('lbn', 'Lebanon', 'https://flagsapi.com/LB/flat/64.png', 'Asia', 59),
  ('pal', 'Palestine', 'https://flagsapi.com/PS/flat/64.png', 'Asia', 62),
  ('kuw', 'Kuwait', 'https://flagsapi.com/KW/flat/64.png', 'Asia', 57),
  ('tkm', 'Turkmenistan', 'https://flagsapi.com/TM/flat/64.png', 'Asia', 56),
  ('kgz', 'Kyrgyzstan', 'https://flagsapi.com/KG/flat/64.png', 'Asia', 60),
  ('tjk', 'Tajikistan', 'https://flagsapi.com/TJ/flat/64.png', 'Asia', 61),
  ('afg', 'Afghanistan', 'https://flagsapi.com/AF/flat/64.png', 'Asia', 52),
  ('ind', 'India', 'https://flagsapi.com/IN/flat/64.png', 'Asia', 56),
  ('mya', 'Myanmar', 'https://flagsapi.com/MM/flat/64.png', 'Asia', 54),
  ('phi', 'Philippines', 'https://flagsapi.com/PH/flat/64.png', 'Asia', 57),
  ('idn', 'Indonesia', 'https://flagsapi.com/ID/flat/64.png', 'Asia', 59),
  ('mas', 'Malaysia', 'https://flagsapi.com/MY/flat/64.png', 'Asia', 56),
  ('sin', 'Singapore', 'https://flagsapi.com/SG/flat/64.png', 'Asia', 55),
  ('ban', 'Bangladesh', 'https://flagsapi.com/BD/flat/64.png', 'Asia', 51),
  ('prk', 'North Korea', 'https://flagsapi.com/KP/flat/64.png', 'Asia', 58),
  ('hkg', 'Hong Kong', 'https://flagsapi.com/HK/flat/64.png', 'Asia', 54),
  ('yem', 'Yemen', 'https://flagsapi.com/YE/flat/64.png', 'Asia', 56),
  ('pak', 'Pakistan', 'https://flagsapi.com/PK/flat/64.png', 'Asia', 42),
  ('sri', 'Sri Lanka', 'https://flagsapi.com/LK/flat/64.png', 'Asia', 49),
  ('mdv', 'Maldives', 'https://flagsapi.com/MV/flat/64.png', 'Asia', 52),
  ('nep', 'Nepal', 'https://flagsapi.com/NP/flat/64.png', 'Asia', 52),
  ('bhu', 'Bhutan', 'https://flagsapi.com/BT/flat/64.png', 'Asia', 47),
  ('cam', 'Cambodia', 'https://flagsapi.com/KH/flat/64.png', 'Asia', 52),
  ('lao', 'Laos', 'https://flagsapi.com/LA/flat/64.png', 'Asia', 50),
  ('tls', 'Timor-Leste', 'https://flagsapi.com/TL/flat/64.png', 'Asia', 39),
  ('bru', 'Brunei', 'https://flagsapi.com/BN/flat/64.png', 'Asia', 47),
  ('mac', 'Macau', 'https://flagsapi.com/MO/flat/64.png', 'Asia', 47),
  ('mon', 'Mongolia', 'https://flagsapi.com/MN/flat/64.png', 'Asia', 48),
  ('tpe', 'Chinese Taipei', 'https://flagsapi.com/TW/flat/64.png', 'Asia', 52),
  ('gum', 'Guam', 'https://flagsapi.com/GU/flat/64.png', 'Asia', 37),
  ('nzl', 'New Zealand', 'https://flagsapi.com/NZ/flat/64.png', 'Asia', 64),
  ('png', 'Papua New Guinea', 'https://flagsapi.com/PG/flat/64.png', 'Asia', 53),
  ('fij', 'Fiji', 'https://flagsapi.com/FJ/flat/64.png', 'Asia', 54),
  ('ncl', 'New Caledonia', 'https://flagsapi.com/NC/flat/64.png', 'Asia', 55),
  ('tah', 'Tahiti', 'https://flagsapi.com/PF/flat/64.png', 'Asia', 54),
  ('slb', 'Solomon Islands', 'https://flagsapi.com/SB/flat/64.png', 'Asia', 55),
  ('van', 'Vanuatu', 'https://flagsapi.com/VU/flat/64.png', 'Asia', 54),
  ('cok', 'Cook Islands', 'https://flagsapi.com/CK/flat/64.png', 'Asia', 50),
  ('sam', 'Samoa', 'https://flagsapi.com/WS/flat/64.png', 'Asia', 48),
  ('ton', 'Tonga', 'https://flagsapi.com/TO/flat/64.png', 'Asia', 40)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  flag = EXCLUDED.flag,
  region = EXCLUDED.region,
  skill = EXCLUDED.skill;

COMMIT;

-- Verify insertion
SELECT
  region,
  COUNT(*) as team_count
FROM teams
GROUP BY region
ORDER BY team_count DESC;

-- Show summary
SELECT
  COUNT(*) as total_teams,
  AVG(skill) as average_skill,
  MIN(skill) as min_skill,
  MAX(skill) as max_skill
FROM teams;
